CREATE TABLE IF NOT EXISTS policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    organization VARCHAR(255) NOT NULL,
    region VARCHAR(100) NOT NULL,
    application_start_date DATE,
    application_end_date DATE,
    recruitment_status VARCHAR(20) NOT NULL,
    source_url VARCHAR(2048) NOT NULL,
    CONSTRAINT chk_policies_application_dates CHECK (
        application_start_date IS NULL
        OR application_end_date IS NULL
        OR application_start_date <= application_end_date
    )
);
